# Generated by Django 5.2.4 on 2025-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('english', models.CharField(max_length=255, verbose_name='English')),
                ('polish', models.CharField(max_length=255, verbose_name='Polish')),
                ('ukrainian', models.CharField(max_length=255, verbose_name='Ukrainian')),
            ],
        ),
    ]
