# Generated by Django 5.2.4 on 2025-07-29 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('url', models.URLField(help_text='The URL of the reference', verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='BasicString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.ForeignKey(help_text='The translatable content of the string', on_delete=django.db.models.deletion.CASCADE, related_name='basic_strings', to='api.multilanguagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('publication_date', models.DateField(null=True, verbose_name='Publication Date')),
                ('title', models.ForeignKey(help_text='The translatable title of the book', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.multilanguagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='The company offering the course', max_length=255, verbose_name='Company')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.ForeignKey(help_text='The translatable description of the course', on_delete=django.db.models.deletion.CASCADE, related_name='courses_description', to='api.multilanguagestring')),
                ('title', models.ForeignKey(help_text='The translatable title of the course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.multilanguagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The start date of the education', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='The end date of the education', verbose_name='End Date')),
                ('degree', models.ForeignKey(help_text='The translatable degree obtained', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations_degree', to='api.multilanguagestring')),
                ('institution', models.ForeignKey(help_text='The translatable name of the educational institution', on_delete=django.db.models.deletion.CASCADE, related_name='educations_institution', to='api.multilanguagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(help_text='The translatable description of the hobby', on_delete=django.db.models.deletion.CASCADE, related_name='hobbies_description', to='api.multilanguagestring')),
                ('name', models.ForeignKey(help_text='The translatable name of the hobby', on_delete=django.db.models.deletion.CASCADE, related_name='hobbies_name', to='api.multilanguagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(help_text='The translatable description of the project', on_delete=django.db.models.deletion.CASCADE, related_name='projects_description', to='api.multilanguagestring')),
                ('name', models.ForeignKey(help_text='The translatable name of the project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.multilanguagestring')),
                ('technologies', models.ManyToManyField(help_text='The translatable technologies used in the project', related_name='projects_technologies', to='api.multilanguagestring')),
                ('references', models.ManyToManyField(help_text='References related to the project', related_name='projects_references', to='api.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(help_text='The translatable name of the technology', on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='api.multilanguagestring')),
                ('structure', models.ForeignKey(help_text='The translatable structure of the technology', on_delete=django.db.models.deletion.CASCADE, related_name='technologies_structure', to='api.multilanguagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_i_know', models.ManyToManyField(help_text='The translatable items I know related to the skill', related_name='skills_know', to='api.multilanguagestring')),
                ('stuff_i_learn', models.ManyToManyField(help_text='The translatable items I am learning related to the skill', related_name='skills_learn', to='api.multilanguagestring')),
                ('stuff_i_plan', models.ManyToManyField(help_text='The translatable items I plan to learn related to the skill', related_name='skills_plan', to='api.multilanguagestring')),
                ('title', models.ForeignKey(help_text='The title of the skill, linked to a technology', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_IT', models.BooleanField(default=False, help_text='Indicates if the work is in the IT field', verbose_name='Is IT')),
                ('skills', models.ManyToManyField(help_text='The translatable skills used in the work', related_name='works_skills', to='api.multilanguagestring')),
                ('title', models.ForeignKey(help_text='The translatable title of the work', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.multilanguagestring')),
            ],
        ),
    ]
