# Generated by Django 5.2.4 on 2025-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reference_basicstring_book_course_education_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='multilanguagestring',
            name='polish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Polish'),
        ),
        migrations.AlterField(
            model_name='multilanguagestring',
            name='ukrainian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ukrainian'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='The translatable technologies used in the project', related_name='projects_technologies', to='api.technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(help_text='The name of the technology', max_length=255, verbose_name='Name'),
        ),
    ]
