# Generated by Django 5.2.4 on 2025-08-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanguagestring',
            name='english',
            field=models.TextField(blank=True, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='multilanguagestring',
            name='polish',
            field=models.TextField(blank=True, null=True, verbose_name='Polish'),
        ),
        migrations.AlterField(
            model_name='multilanguagestring',
            name='ukrainian',
            field=models.TextField(blank=True, null=True, verbose_name='Ukrainian'),
        ),
    ]
