# Generated by Django 5.2.4 on 2025-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_multilanguagestring_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Progress of reading the book in percentage (0-100)', verbose_name='Reading Progress'),
        ),
    ]
