# Generated by Django 5.2.4 on 2025-08-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='icon_path',
            field=models.CharField(blank=True, help_text='Path to the icon representing the hobby', max_length=255, null=True, verbose_name='Icon Path'),
        ),
        migrations.AlterField(
            model_name='book',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Progress of reading the book (0-1)', verbose_name='Reading Progress'),
        ),
    ]
