# Generated by Django 5.2.4 on 2025-08-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hobby_icon_path_alter_book_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='icon_path',
            field=models.CharField(default='empty.svg', help_text='Path to the icon representing the hobby', max_length=255, null=True, verbose_name='Icon Path'),
        ),
    ]
