# Generated by Django 5.2.4 on 2025-08-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_hobby_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='icon_path',
            field=models.CharField(blank=True, help_text='Path to the icon representing the hobby', max_length=255, null=True, verbose_name='Icon Path'),
        ),
    ]
