# Generated by Django 5.2.4 on 2025-08-02 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_hobby_icon_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='structure',
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the technology type, e.g., programming language, framework, etc.', max_length=255, verbose_name='Title')),
                ('name', models.ForeignKey(help_text='The translatable name of the technology type', on_delete=django.db.models.deletion.CASCADE, related_name='technology_types', to='api.multilanguagestring')),
            ],
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_type',
            field=models.ForeignKey(help_text='The type of the technology, e.g., programming language, framework, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='Technologies', to='api.technologytype'),
            preserve_default=False,
        ),
    ]
