# Generated by Django 5.2.4 on 2025-08-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_technology_structure_technologytype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='stuff_i_know',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='stuff_i_learn',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='stuff_i_plan',
        ),
        migrations.AddField(
            model_name='skill',
            name='stuff_i_know',
            field=models.ForeignKey(default=0, help_text='The translatable items I know related to the skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills_know', to='api.multilanguagestring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='stuff_i_learn',
            field=models.ForeignKey(default=0, help_text='The translatable items I am learning related to the skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills_learn', to='api.multilanguagestring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='stuff_i_plan',
            field=models.ForeignKey(default=0, help_text='The translatable items I plan to learn related to the skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills_plan', to='api.multilanguagestring'),
            preserve_default=False,
        ),
    ]
