# Generated by Django 5.2.4 on 2025-08-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_skill_stuff_i_know_remove_skill_stuff_i_learn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reference',
            name='title',
        ),
        migrations.AlterField(
            model_name='reference',
            name='host',
            field=models.ForeignKey(help_text='The host of the reference', on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.host'),
        ),
    ]
