# Generated by Django 5.2.4 on 2025-08-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_host_remove_reference_title_alter_reference_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_paths',
            field=models.JSONField(blank=True, default=list, help_text='List of image paths related to the project'),
        ),
    ]
