# Generated by Django 5.2.4 on 2025-08-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_image_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_paths',
            field=models.TextField(blank=True, help_text="Paths to images related to the project. Separated by ';'.", null=True),
        ),
    ]
