# Generated by Django 5.2.4 on 2025-08-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_project_image_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='skills',
        ),
        migrations.AddField(
            model_name='work',
            name='skills',
            field=models.ForeignKey(default=0, help_text='The translatable skills used in the work', on_delete=django.db.models.deletion.CASCADE, related_name='works_skills', to='api.multilanguagestring'),
            preserve_default=False,
        ),
    ]
