# Generated by Django 5.2.4 on 2025-08-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_work_skills_work_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.ForeignKey(blank=True, help_text='The translatable description of the course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_description', to='api.multilanguagestring'),
        ),
    ]
