# Generated by Django 5.2.4 on 2025-08-05 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.ForeignKey(help_text='The translatable field of study', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations_field_of_study', to='api.multilanguagestring'),
        ),
    ]
