# Generated by Django 5.2.4 on 2025-08-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_education_field_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='The identification of the contact', max_length=255, verbose_name='Identification')),
                ('icon_path', models.CharField(blank=True, help_text='The path to the icon representing the contact', max_length=255, null=True, verbose_name='Icon Path')),
            ],
        ),
        migrations.DeleteModel(
            name='BasicString',
        ),
    ]
