# Generated by Django 5.2.4 on 2025-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contact_delete_basicstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Copy from this: BVU44J', max_length=6, unique=True, verbose_name='Company Code')),
                ('name', models.CharField(help_text='The name of the company', max_length=255, verbose_name='Company Name')),
                ('company_color', models.CharField(help_text='The primary color of the company in HEX format', max_length=6, verbose_name='Primary Color')),
                ('cv_path', models.CharField(blank=True, help_text='The path to the my CV specially for company', max_length=255, null=True, verbose_name='CV Path')),
                ('cover_letter_path', models.CharField(blank=True, help_text='The path to the my cover letter specially for company', max_length=255, null=True, verbose_name='Cover Letter Path')),
                ('skills', models.ManyToManyField(blank=True, help_text='The skills associated with the company', to='api.skill', verbose_name='Skills')),
            ],
        ),
    ]
