# Generated by Django 5.2.4 on 2025-09-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='icon_path',
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_name',
            field=models.CharField(blank=True, help_text='The icon name in react-icons library', max_length=255, null=True, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: PJE0AK', max_length=6, unique=True, verbose_name='Company Code'),
        ),
    ]
