# Generated by Django 5.2.4 on 2025-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_contact_icon_path_contact_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologytype',
            name='hue_color',
            field=models.CharField(default=0, help_text='The color from HSL palette. Must be between 0 and 360', max_length=255, verbose_name='Hue Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: ZPVSUG', max_length=6, unique=True, verbose_name='Company Code'),
        ),
    ]
