# Generated by Django 5.2.4 on 2025-09-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_technologytype_hue_color_alter_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: 8G8ACG', max_length=6, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stuff_i_learn',
            field=models.ForeignKey(blank=True, help_text='The translatable items I am learning related to the skill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_learn', to='api.multilanguagestring'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stuff_i_plan',
            field=models.ForeignKey(blank=True, help_text='The translatable items I plan to learn related to the skill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_plan', to='api.multilanguagestring'),
        ),
    ]
