# Generated by Django 5.2.4 on 2025-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_company_code_alter_skill_stuff_i_learn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='icon_path',
        ),
        migrations.AddField(
            model_name='hobby',
            name='images_path',
            field=models.CharField(blank=True, help_text="Path to the images (divide image path by semicolon ';')", max_length=255, null=True, verbose_name='Images Path'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: JNHCRY', max_length=6, unique=True, verbose_name='Company Code'),
        ),
    ]
