# Generated by Django 5.2.4 on 2025-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_hobby_icon_path_hobby_images_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: L52QNT', max_length=6, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='images_path',
            field=models.TextField(blank=True, help_text="Path to the images (divide image path by semicolon ';')", max_length=255, null=True, verbose_name='Images Path'),
        ),
    ]
