# Generated by Django 5.2.4 on 2025-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_company_code_alter_hobby_images_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of language', max_length=255, unique=True)),
                ('knowledge', models.CharField(help_text='The knowledge of language', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: E2KUPI', max_length=6, unique=True, verbose_name='Company Code'),
        ),
    ]
