# Generated by Django 5.2.4 on 2025-09-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_language_alter_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: ZT1PVG', max_length=6, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.ForeignKey(help_text='The name of language', on_delete=django.db.models.deletion.CASCADE, related_name='language_name', to='api.multilanguagestring'),
        ),
    ]
