# Generated by Django 5.2.4 on 2025-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_company_code_alter_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cover_letter_path',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cv_path',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_letter_file',
            field=models.FileField(default=None, upload_to='', verbose_name=models.FileField(upload_to='documents/pdfs/')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='cv_file',
            field=models.FileField(default=0, upload_to='', verbose_name=models.FileField(upload_to='documents/pdfs/')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: C8F2EC', max_length=6, unique=True, verbose_name='Company Code'),
        ),
    ]
