# Generated by Django 5.2.4 on 2025-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_company_cover_letter_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Copy from this: G24HCU', max_length=6, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cover_letter_file',
            field=models.FileField(upload_to='documents/pdfs/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cv_file',
            field=models.FileField(upload_to='documents/pdfs/'),
        ),
    ]
